### ISSUE TITLE
add more Unit tests to increase test coverage to at least 75%

### ISSUE THREAD

**Issue by L-Huber** [sopra-fs23-group-20/server#141]

**Comment by JonathanContrerasM** [comment]
31bbcc8 2b46c5d a27de04 e489037 5810ab7

**Comment by JonathanContrerasM** [comment]
787184c

**Comment by dariomonopoli-dev** [comment]
85add45f57a2bb97c1ded48c644a94dce3c21123

**Comment by L-Huber** [comment]
https://github.com/sopra-fs23-group-20/server/commit/f3e8767a372e595feab39b41fc3a66b9056da98d

**Comment by robonder** [comment]
https://github.com/sopra-fs23-group-20/server/commit/cef1fd006cc0ecc852429b4c662c9671fb38f9e6
