### ISSUE TITLE
User can delete specific games from their history or erase the complete history

### ISSUE THREAD

**Issue by dariomonopoli-dev** [sopra-fs23-group-20/server#28]

**Comment by JSha91** [comment]
@robonder 
I do not see the logic behind this ticket. This needs to be worked on in the backend and how would you like to implement it ------> either you delete the game as a whole and all participants from this game cannot see the history anymore or you can delete a specific participant and then have a distorted representation of the facts (e.g. if the removed participant was first placed..). 
I could have disabled the gameHistory for a specific User in the FrontEnd but then it would have still been visible for the other Users.
Do you get my point? 
In my opinion, we can close this ticket and not consider it further.
