### ISSUE TITLE
If I guess correctly within 5 seconds I get 100 points

### ISSUE THREAD

**Issue by dariomonopoli-dev** [sopra-fs23-group-20/server#72]

**Comment by JSha91** [comment]
68bcc4ba3db05582590193ccbaddb14681cf70b2

**Comment by JSha91** [comment]
68bcc4ba3db05582590193ccbaddb14681cf70b2

**Comment by JSha91** [comment]
05f41deb8284ba8c072517ac35536871bd0c598f

**Comment by JSha91** [comment]
Deployment failed, since one Test was not modified. But meanwhile Test is modified and everything is ok again.
