### ISSUE TITLE
US3c: Join a Game Lobby: As a user, I want to join a game lobby created by another player by entering the shared game code.

### ISSUE THREAD

**Issue by dariomonopoli-dev** [sopra-fs23-group-20/server#75]
### Acceptance Criteria
- [x] sopra-fs23-group-20/server#89
- [x] sopra-fs23-group-20/client#3

**Comment by dariomonopoli-dev** [comment]
### Acceptance Criteria
- [ ] User can join a game lobby using the shared game code
- [ ] User can see which other players are in the lobby

**Comment by L-Huber** [comment]
all tasks done
