### ISSUE TITLE
If my guess is incorrect, I will receive no points

### ISSUE THREAD

**Issue by dariomonopoli-dev** [sopra-fs23-group-20/server#81]

**Comment by JSha91** [comment]
8750de9edf92ab6b2b81d338f839d692f4dbe46a

**Comment by JSha91** [comment]
05f41deb8284ba8c072517ac35536871bd0c598f

**Comment by JSha91** [comment]
05f41deb8284ba8c072517ac35536871bd0c598f

**Comment by JSha91** [comment]
Merge failed, since Test was not modified. But meanwhile everything is ok again. Thanks
